#!/bin/sh -e

echo "$1" | grep -q '\.arte\.'
alias perl="$alias_perl"

page=$(wget -q -O- "$1")

title=$(echo "$page" | perl -ne 'y{/}{:}; if(m{<h1>(.*)<:h1>}){print decode_entities($1)}')
: ${title:=$(basename "$1" .html)}

date=$(echo "$page" | perl -ne 'if(m{\W(\d\d)-(\d\d)-(\d\d)\W}){print "20$3-$2-$1"; exit}')
: ${date:?}

video=$(echo "$page" | perl -ne 'if(m{vars_player.videorefFileUrl\s*=\s*"(.*?)"}){print $1}' | wget -q -i- -O- | perl -ne 'if(m{lang="fr".*?ref="(.*?)"}){print $1}' | wget -q -i- -O- | perl -ne 'if(m{quality="hd".*?>(.*?)<}){print $1}')

player=$(echo "$page" | perl -ne 'if(m{var url_player\s*=\s*"(.*?)"}){print $1}')

download-one "$video" "$player" "$XDG_VIDEOS_DIR/$title $date.mp4"
