#!/bin/sh -e

echo "$1" | grep -q '\.arte\.'
alias perl="$alias_perl"

json=$(wget -q -O- "$1" | perl -ne 'if(m{arte_vp_url="(.*?)"}){print $1; exit}')

title=$(wget -q -O- "$json" | perl -ne 'y{/}{\N{U+2215}}; m{"VTI":"(.*?)"}; print $1; if(m{"VSU":"(.*?)"}){print " - $1"}')
: ${title:?}

video=$(wget -q -O- "http://www.arte.tv/player/v2/smil.smil?json_url=$json&smil_entries=RTMP_SQ_1,RTMP_MQ_1,RTMP_LQ_1" | tr -d [:space:] | perl -ne 'm{base="(.*?)".*?src="(.*?)"}; print "$1$2"')
: ${video:?}

download-one "$video" 'http://www.arte.tv/player/v2/jwplayer6/mediaplayer.6.3.3242.swf' "$XDG_VIDEOS_DIR/$title.mp4"
